import Navbar from '@/component/Navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Login',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
        {children}
    </>
  )
}
