export const ADD_TO_CART_BEGIN = 'ADD_TO_CART_BEGIN';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const FETCH_USER_CART = 'FETCH_USER_CART';
export const DELETE_PRODUCTS_CART = 'DELETE_PRODUCTS_CART';
export const INCREASE_ITEM = "INCREASE_ITEM";
export const DCREASE_ITEM = "DCREASE_ITEM"