export const FETCH_PRODUCTS_BEGIN   = 'FETCH_PRODUCTS_BEGIN';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const  FETCH_QUERY_PRODUCTS_SUCCESS = 'FETCH_QUERY_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_BY_ID_SUCCESS = "FETCH_PRODUCTS_BY_ID_SUCCESS";